- name: Install computing tools packages
  ansible.builtin.apt:
    state:
      present
    pkg: "{{ item }}"
  with_items:
    - arping
    - tcpdump
    - wireshark
    - iptables
    - nmap
    - openssl
    - tcpdump
    - traceroute
    - tcptraceroute
    - whois
  notify:
    - "apt sync"
